pic_app/urls.py
from django.urls import path
from pic_app import views

app_name = 'pic_app'
urlpatterns = [
    path('', views.imageList.as_view(), name='imageList'),
    path("new", views.imageAdd.as_view(), name="imageAdd"),
    path('show/<int:id>', views.imageDetail.as_view(), name="imageDetail"),
    path('delete/<int:id>', views.imageDelete.as_view(), name="imageDelete"),
    path('<int:id>/edit', views.imageEdit.as_view(), name="imageEdit"),
    

]

picture_viewer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pic_app.urls', namespace="pic_app")),
    
]

pic_app/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    ImgName = models.CharField(max_length=100)
    ImgURL = models.URLField()
    ImgDetails = models.TextField(max_length=500)

    class Meta:
        ordering = ('-id',)

pic_app/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer
from django.shortcuts import redirect

from pic_app.models import Image
from pic_app.serializers import ImageSerializer
from pic_app.pagination import CustomPagination, MyPaginationMixin


class imageList(APIView, MyPaginationMixin):

    pagination_class = CustomPagination
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        query = request.GET.get("query", None)
        if(not query):
            images = Image.objects.all()
            page = self.paginate_queryset(images)
            if page is not None:
                serializers = ImageSerializer(page, many=True)
                image_response = self.get_paginated_response(serializers.data)
            
            return Response(image_response.data, template_name="image_list.html", status=status.HTTP_200_OK)
        
        # Sending a list of images whose name match with the query
        images = Image.objects.filter(ImgName=query)
        serializers = ImageSerializer(images, many=True)
        data = {
            "results": serializers.data,
            "query": query
        }
        return Response(data, template_name="image_list.html", status=status.HTTP_200_OK)
        
    def post(self, request):
        data = {
            "ImgName": request.data.get("ImgName"),
            "ImgURL": request.data.get("ImgURL"),
            "ImgDetails": request.data.get("ImgDetails")
        }
        serializer = ImageSerializer(data=data)
        if(serializer.is_valid()):
            serializer.save()
        return redirect("pic_app:imageList")
    
class imageDetail(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, id):
        try:
            image = Image.objects.get(id=id)
        except Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
        serializer = ImageSerializer(image)
        return Response({"image": serializer.data}, template_name="image_detail.html", status=status.HTTP_200_OK)

class imageDelete(APIView):

    def delete(self, request, id):
        try:
            image = Image.objects.get(id=id)
        except Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        image.delete()
        return JsonResponse({"status": "Success"})

class imageAdd(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):
        return Response(template_name="image_add.html", status=status.HTTP_200_OK)

class imageEdit(APIView):

    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, id):
        try:
            image = Image.objects.get(id=id)
        except Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
        serializer = ImageSerializer(image)
        return Response({"image": serializer.data}, template_name="image_edit.html", status=status.HTTP_200_OK)
    
    def put(self, request, id):
        try:
            image = Image.objects.get(id=id)
        except Image.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        data = {
            "ImgName": request.data.get("ImgName"),
            "ImgURL": request.data.get("ImgURL"),
            "ImgDetails": request.data.get("ImgDetails")
        }
        serializer = ImageSerializer(image, data, partial=True)
        if(serializer.is_valid()):
            serializer.save()
        return JsonResponse({"status": "passed"})
        

pic_app/templates/image_add.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Add Image</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <h1 class="text-center">Add Image</h1>
        <div class="container" style="width:50%; background-color: rgba(127, 143, 185, 0.842);">
            <form action="{% url 'pic_app:imageList' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
          
                <div class="form-group">
                  <label for="ImgName">Image Name</label>
                  <input type="text" class="form-control" id="ImgName" name="ImgName" placeholder="Image Name" required>
                </div>
          
                <div class="form-group">
                  <label for="ImgURL">Image URL</label>
                  <input type="url" class="form-control" id="ImgURL" name="ImgURL" value="" placeholder="Image URL" required>
                </div>
          
                <div class="form-group">
                  <label for="ImgDetails">Image Details</label>
                  <input type="text" class="form-control" id="ImgDetails" name="ImgDetails" value="" placeholder="Image Details" required>
                </div>
          
                <div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </form>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'pic_app:imageList' %}">See all images :)</a>
        </div>

    </body>
</html>

pic_app/templates/image_detail.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Images List</title>
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
        <meta name="sviewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            function csrfcookie(name){
                var cookieValue = null;

                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var editbutton = document.getElementById("editBtn");
            function editImage(id) {
                console.log(id);
                return false;
                
            }

            var delbutton = document.getElementById("delBtn");
            function deleteImage(id) {
                var csrftoken = csrfcookie('csrftoken');
                var url = `/delete/${id}`;
                fetch(url,{
                    method: 'DELETE',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    }
                }).then(function(response){
                    location.href="/";
                });
            }
        </script>
    </head>
    <style>
        #myBtn {
            display: block;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            font-size: 18px;
            border: none;
            outline: none;
            background-color: red;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 4px;
            }

        #myBtn:hover {
            background-color: #555;
        }
        /* .card-custom {
            max-width: 128px;
        } */
    </style>
    <body>        
        <h1 class="text-center">Images List</h1>
        <div class="text-center">
            <a class="btn btn-primary" style="margin-top: 25px; margin-bottom: 25px;" href="{% url 'pic_app:imageList' %}">See all Images :)</a>
        </div>
        <div class="text-center">
            <div class="card" style="margin-left:30%; margin-right:30%; text-align:center">
                <img src="{{image.ImgURL}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{image.ImgName}}</h5>
                    <p class="card-text">{{image.ImgDetails}}</p>
                    <a href="{% url 'pic_app:imageEdit' image.id %}">
                        <input class="btn btn-primary" id="editBtn" type="button" value="Edit">
                    </a>
                    <input class="btn btn-danger" id="delBtn" onclick="return deleteImage({{image.id}})" type="button" value="Delete">
                </div>
            </div>
        </div>
    </body>
</html>

pic_app/templates/image_edit.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Add Image</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            function csrfcookie(name){
                var cookieValue = null;

                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            function imageEdit(id) {
                var ImgName = document.getElementById("ImgName").value;
                var ImgURL = document.getElementById("ImgURL").value;
                var ImgDetails = document.getElementById("ImgDetails").value;
                var data = {};
                data["ImgName"] = ImgName;
                data["ImgURL"] = ImgURL;
                data["ImgDetails"] = ImgDetails;
                console.log(data);
                var csrftoken = csrfcookie('csrftoken');
                var url = `/${id}/edit`;
                fetch(url,{
                    method: 'PUT',
                    credentials: 'same-origin',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify(data),
                }).then(function(response){
                    location.href="/";
                })
            }
        </script>
    </head>
    
    <body>
        <h1 class="text-center">Edit Image</h1>
        <div class="container" style="width:50%; background-color: rgba(127, 143, 185, 0.842);">
            <form name="edit_form" onsubmit="return imageEdit({{image.id}})" enctype="multipart/form-data">
                {% csrf_token %}
          
                <div class="form-group">
                  <label for="ImgName">Image Name</label>
                  <input type="text" class="form-control" id="ImgName" name="ImgName" placeholder="Image Name" value="{{image.ImgName}}" readonly>
                </div>
          
                <div class="form-group">
                  <label for="ImgURL">Image URL</label>
                  <input type="url" class="form-control" id="ImgURL" name="ImgURL" value="{{image.ImgURL}}" placeholder="Image URL" required>
                </div>
          
                <div class="form-group">
                  <label for="ImgDetails">Image Details</label>
                  <input type="text" class="form-control" id="ImgDetails" name="ImgDetails" value="{{image.ImgDetails}}" placeholder="Image Details" required>
                </div>
          
                <div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </form>
        </div>
        <br>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'pic_app:imageList' %}">See all images :)</a>
        </div>

    </body>
</html>

pic_app/templates/image_list.html
{% load rest_framework %}

<html lang="en">
    <head>
        <title>Images List</title>
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
        <meta name="sviewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script>
            var mybutton = document.getElementById("myBtn");

            // When the user scrolls down 20px from the top of the document, show the button
            window.onscroll = function() {scrollFunction()};

            function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
            }

            // When the user clicks on the button, scroll to the top of the document
            function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
            }
        </script>
    </head>
    <style>
        #myBtn {
            display: block;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            font-size: 18px;
            border: none;
            outline: none;
            background-color: red;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 4px;
            }

        #myBtn:hover {
            background-color: #555;
        }
        /* .card-custom {
            max-width: 128px;
        } */
    </style>
    <body>
        <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
        
        <h1 class="text-center">Images List</h1>
        <div class="text-center">
            <a class="btn btn-primary" href="{% url 'pic_app:imageAdd' %}">Want to add a new Image :)</a>
        </div>
        <br>
        {% if query %}
            <div class="text-center">
                <a class="btn btn-primary" href="{% url 'pic_app:imageList' %}">See all Images :)</a>
            </div>
            <br>
            <h2 class="text-center">Search Results for query={{query}}</h2>            
        {% endif %}

        <div class="text-center">
            <div class="row row-cols-1 row-cols-md-3 g-4 m-5 pb-5">
                {% for image in results %}
                <div class="col">
                    <div class="card" style="max-width: 18rem;">
                        <a href="{% url 'pic_app:imageDetail' image.id %}">
                            <img
                                src="{{image.ImgURL}}"
                                class="card-img-top"
                            />
                        </a>
                    </div>
                    <br>
                </div>
                {% endfor %}
            </div>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center pagination-lg">
                {% if previous %}
                    <li class="page-item">
                        <a class="page-link" href={{previous}} tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                {% if next %}
                    <li class="page-item">
                        <a class="page-link" href={{next}} tabindex="-1">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </body>
</html>